import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ClientProvider from '@/providers/providers';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import '@/assets/styles/global.sass'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ClientProvider>
                    <ToastContainer
                        autoClose={2500}
                        theme="colored"
                        hideProgressBar={false}
                        position={'top-right'}
                    />
                    {children}
                </ClientProvider>
            </body>
        </html>
    );
}
